### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by poodlepoodle** [goormthon-Univ/TEAM_1_2#1]
## 💡 Issue: 이슈 요약
프로젝트 초기 세팅을 설정합니다.

## 📝 Todo: 할 작업
- [x] Vite - Vercel 빌드 세팅
- [x] 디렉토리 구조 잡기
- [x] 초기 의존성 추가하기

## 🔖 Reference: 참고 자료
.
