### ISSUE TITLE
소셜 로그인 연결 개선, HTTP 요청 공통 로직 분리

### ISSUE THREAD

**Issue by poodlepoodle** [goormthon-Univ/TEAM_1_2#14]
## 💡 Issue: 이슈 요약
앞선 이슈(#4)에 이어서 카카오 소셜 로그인 연결 플로우를 개선합니다.

## 📝 Todo: 할 작업
- [ ] `LoginPage`에서 카카오 소셜 로그인 리다이렉팅 플로우를 수정합니다.
- [ ] API 접근을 위한 Access Token을 보관합니다.
- [ ] 백엔드 API에 공통으로 활용할 수 있는 로직을 분리합니다.
- [ ] 첫 로그인 페이지 기능을 구현합니다.

## 🔖 Reference: 참고 자료
.
