### ISSUE TITLE
모든 세부 페이지 라우팅 연결 및 마크업 구현

### ISSUE THREAD

**Issue by poodlepoodle** [goormthon-Univ/TEAM_1_2#16]
## 💡 Issue: 이슈 요약
존재하는 모든 페이지에 대해서 라우팅을 연결하고, 목업 데이터로 마크업 구현을 완료합니다.

## 📝 Todo: 할 작업
- [x] 모든 세부 페이지에 대한 라우팅을 연결합니다.
- [x] 모든 세부 페이지에 대한 기본적인 마크업 구현을 완료합니다.
- [x] 모든 세부 페이지에 대한 API 목업 데이터를 연결합니다.

## 🔖 Reference: 참고 자료
.
