### ISSUE TITLE
홈 페이지 기능 구현

### ISSUE THREAD

**Issue by poodlepoodle** [goormthon-Univ/TEAM_1_2#17]
## 💡 Issue: 이슈 요약
백엔드 API 요청을 통한 홈 페이지 기능을 모두 구현합니다.

## 📝 Todo: 할 작업
- [ ] 연도별 보기 메뉴를 구현합니다.
- [ ] 절기별 보기 메뉴를 구현합니다.
- [ ] 오늘의 운세 기능을 구현합니다.

## 🔖 Reference: 참고 자료
.
