### ISSUE TITLE
상태 관리 도구 추가, 소셜 로그인 연결

### ISSUE THREAD

**Issue by poodlepoodle** [goormthon-Univ/TEAM_1_2#4]
## 💡 Issue: 이슈 요약
상태 관리 도구를 앱에 추가하고 백엔드 소셜 로그인 서버에서 받아온 정보를 보관합니다.

## 📝 Todo: 할 작업
- [x] 상태 관리 도구 추가
- [ ] 소셜 로그인 연결하기
- [x] 로그인 페이지 구현
- [ ] 로그인 정보 보관하기

## 🔖 Reference: 참고 자료
.
